language: node_js
node_js:
  - "10"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y sshpass
deploy:
  on:
    branch: master
  provider: script
  skip_cleanup: true
  script: sshpass -p $SP ssh -t $SU@$SH -p $SPP '. ~/.nvm/nvm.sh; cd ~/apps/entrybot; git pull origin master; npm i; pm2 restart npm;'

