language: node_js
node_js:
  - "10"
before_install:
  - sudo apt-get install -y sshpass
deploy:
  on: master
  script:
    - sshpass -p $SP ssh -t SU@SH -p $SPP 'cd ~/apps/entrybot; git pull origin master; npm i; pm2 restart npm;'

