language: node_js
node_js:
- '10'
deploy:
  on:
    branch: master
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_d6d9e7210ef6_key -iv $encrypted_d6d9e7210ef6_iv
  -in deploy_key.enc -out deploy_key -d
- chmod 600 ./deploy_key
- eval "$(ssh-agent -s)"
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
