
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "entrybot.serviceAccountName" . }}
  labels:
{{ include "entrybot.labels" . | nindent 4 }}
{{- end -}}